title: My WildCat Studios Portfolio description: >-
         This is my portfolio showcasing my projects and skills.
baseurl: "" # leave empty since this is your user page
url: "https://Jb.147429.github.io" # replace YOURUSERNAME with your GitHub username
theme: hacker # replace with your chosen theme from the list
